export interface Exercise {
  id: string;
  name: string;
  sets: number;
  reps: string;
  rest: string;
  tip: string;
  substitutes: string[];
  muscleGroup: string;
}

export interface TrainingDay {
  id: string;
  name: string;
  label: string;
  focus: string;
  exercises: Exercise[];
  cardioNote?: string;
}

export const defaultTrainingPlan: TrainingDay[] = [
  {
    id: 'push',
    name: 'PUSH',
    label: 'Segunda',
    focus: 'Peito + Ombro + Tríceps',
    cardioNote: '🔥 Pós-treino: 20 min caminhada inclinada',
    exercises: [
      {
        id: 'push1',
        name: 'Supino Reto',
        sets: 4,
        reps: '12-10-8-8',
        rest: '90s',
        tip: 'Progressão de carga: aumente peso a cada série. Desça a barra até o peito, cotovelos a 45°.',
        substitutes: ['Supino com Halteres', 'Supino Máquina'],
        muscleGroup: 'Peitoral',
      },
      {
        id: 'push2',
        name: 'Supino Inclinado Halter',
        sets: 3,
        reps: '10',
        rest: '75s',
        tip: 'Banco a 30-45°. Abra bem na descida, junte no topo. Foco em peitoral superior.',
        substitutes: ['Supino Inclinado Barra', 'Crossover de Baixo p/ Cima'],
        muscleGroup: 'Peitoral Superior',
      },
      {
        id: 'push3',
        name: 'Desenvolvimento Halter',
        sets: 3,
        reps: '10',
        rest: '75s',
        tip: 'Sentado, costas apoiadas. Suba até quase travar os cotovelos.',
        substitutes: ['Desenvolvimento Barra', 'Desenvolvimento Arnold'],
        muscleGroup: 'Deltóide',
      },
      {
        id: 'push4',
        name: 'Elevação Lateral',
        sets: 3,
        reps: '12-15',
        rest: '60s',
        tip: 'Cotovelos levemente flexionados. Suba até a altura dos ombros. Sem impulso!',
        substitutes: ['Elevação Lateral Cabo', 'Elevação Lateral Máquina'],
        muscleGroup: 'Deltóide Lateral',
      },
      {
        id: 'push5',
        name: 'Tríceps Corda',
        sets: 3,
        reps: '12',
        rest: '60s',
        tip: 'Abra a corda nas pontas. Cotovelos fixos ao corpo.',
        substitutes: ['Tríceps Barra Reta', 'Tríceps Francês'],
        muscleGroup: 'Tríceps',
      },
      {
        id: 'push6',
        name: 'Paralelas',
        sets: 3,
        reps: 'até falha',
        rest: '60s',
        tip: 'Corpo levemente inclinado pra frente. Se não aguentar, use máquina assistida.',
        substitutes: ['Mergulho Máquina', 'Supino Declinado'],
        muscleGroup: 'Peitoral + Tríceps',
      },
    ],
  },
  {
    id: 'pull',
    name: 'PULL',
    label: 'Terça',
    focus: 'Costas + Bíceps + HIIT',
    cardioNote: '🔥 HIIT (15 min): 30s sprint / 1min leve',
    exercises: [
      {
        id: 'pull1',
        name: 'Puxada Frente',
        sets: 4,
        reps: '10',
        rest: '90s',
        tip: 'Puxe até o peito, escápulas retraídas. Segure 1s embaixo.',
        substitutes: ['Barra Fixa', 'Puxada Triângulo'],
        muscleGroup: 'Dorsal',
      },
      {
        id: 'pull2',
        name: 'Remada Curvada',
        sets: 3,
        reps: '10',
        rest: '90s',
        tip: 'Tronco a 45°. Puxe a barra para o abdômen. Sem impulso.',
        substitutes: ['Remada Cavalinho', 'Remada Unilateral'],
        muscleGroup: 'Dorsal',
      },
      {
        id: 'pull3',
        name: 'Remada Baixa',
        sets: 3,
        reps: '12',
        rest: '75s',
        tip: 'Peito pra frente. Puxe até o abdômen, squeeze nas costas.',
        substitutes: ['Remada Sentada Aberta', 'Pullover Máquina'],
        muscleGroup: 'Dorsal',
      },
      {
        id: 'pull4',
        name: 'Face Pull',
        sets: 3,
        reps: '12',
        rest: '60s',
        tip: 'Puxe para o rosto, rotação externa. Essencial pra postura!',
        substitutes: ['Crucifixo Inverso', 'Band Pull Apart'],
        muscleGroup: 'Deltóide Posterior',
      },
      {
        id: 'pull5',
        name: 'Rosca Direta',
        sets: 3,
        reps: '10',
        rest: '60s',
        tip: 'Cotovelos fixos. Suba com controle, desça em 2s.',
        substitutes: ['Rosca Scott', 'Rosca Barra W'],
        muscleGroup: 'Bíceps',
      },
      {
        id: 'pull6',
        name: 'Rosca Alternada',
        sets: 3,
        reps: '12',
        rest: '60s',
        tip: 'Alternada com supinação. Mantenha cotovelos grudados no corpo.',
        substitutes: ['Rosca Martelo', 'Rosca Concentrada'],
        muscleGroup: 'Bíceps',
      },
    ],
  },
  {
    id: 'legs',
    name: 'LEGS',
    label: 'Quarta',
    focus: 'Pernas Completo',
    cardioNote: '🔥 Cardio leve: 15-20 min caminhada/elíptico',
    exercises: [
      {
        id: 'legs1',
        name: 'Agachamento',
        sets: 4,
        reps: '12-10-8-8',
        rest: '120s',
        tip: 'Progressão de carga. Pés na largura dos ombros. Desça até 90°. Core contraído.',
        substitutes: ['Leg Press 45°', 'Agachamento Smith'],
        muscleGroup: 'Quadríceps',
      },
      {
        id: 'legs2',
        name: 'Leg Press',
        sets: 3,
        reps: '10',
        rest: '90s',
        tip: 'Pés no meio da plataforma. Não trave os joelhos no topo.',
        substitutes: ['Hack Squat', 'Agachamento Búlgaro'],
        muscleGroup: 'Quadríceps',
      },
      {
        id: 'legs3',
        name: 'Stiff',
        sets: 3,
        reps: '10',
        rest: '75s',
        tip: 'Joelhos levemente flexionados. Desça a barra ao longo das pernas. Sinta o posterior esticar.',
        substitutes: ['Romeno com Halteres', 'Good Morning'],
        muscleGroup: 'Posterior',
      },
      {
        id: 'legs4',
        name: 'Extensora',
        sets: 3,
        reps: '12',
        rest: '60s',
        tip: 'Suba totalmente e segure 1s no topo. Desça controlado.',
        substitutes: ['Extensão Unilateral', 'Sissy Squat'],
        muscleGroup: 'Quadríceps',
      },
      {
        id: 'legs5',
        name: 'Flexora',
        sets: 3,
        reps: '12',
        rest: '60s',
        tip: 'Quadril colado no banco. Contraia glúteos e posteriores.',
        substitutes: ['Flexora em Pé', 'Mesa Flexora'],
        muscleGroup: 'Posterior',
      },
      {
        id: 'legs6',
        name: 'Panturrilha',
        sets: 4,
        reps: '15',
        rest: '45s',
        tip: 'Amplitude máxima. Segure 2s no topo, desça esticando.',
        substitutes: ['Panturrilha Sentado', 'Panturrilha no Leg'],
        muscleGroup: 'Panturrilha',
      },
    ],
  },
  {
    id: 'upper',
    name: 'UPPER',
    label: 'Quinta',
    focus: 'Superiores Geral + HIIT',
    cardioNote: '🔥 HIIT (15 min): 30s sprint / 1min leve',
    exercises: [
      {
        id: 'upper1',
        name: 'Supino Máquina',
        sets: 3,
        reps: '12',
        rest: '75s',
        tip: 'Foco em conexão mente-músculo. Carga moderada, execução perfeita.',
        substitutes: ['Supino Reto Halter', 'Crossover'],
        muscleGroup: 'Peitoral',
      },
      {
        id: 'upper2',
        name: 'Remada Máquina',
        sets: 3,
        reps: '12',
        rest: '75s',
        tip: 'Peito apoiado. Puxe com as costas, não com os braços.',
        substitutes: ['Remada Baixa', 'Remada Unilateral'],
        muscleGroup: 'Dorsal',
      },
      {
        id: 'upper3',
        name: 'Elevação Lateral',
        sets: 3,
        reps: '15',
        rest: '60s',
        tip: 'Volume extra para deltóide lateral. Técnica > carga.',
        substitutes: ['Elevação Lateral Cabo', 'Elevação Lateral Máquina'],
        muscleGroup: 'Deltóide Lateral',
      },
      {
        id: 'upper4',
        name: 'Rosca Direta',
        sets: 3,
        reps: '10',
        rest: '60s',
        tip: 'Cotovelos fixos. Suba com controle.',
        substitutes: ['Rosca Scott', 'Rosca Martelo'],
        muscleGroup: 'Bíceps',
      },
      {
        id: 'upper5',
        name: 'Tríceps Testa',
        sets: 3,
        reps: '10',
        rest: '60s',
        tip: 'Desça a barra até a testa. Cotovelos apontando pro teto.',
        substitutes: ['Tríceps Corda', 'Tríceps Kickback'],
        muscleGroup: 'Tríceps',
      },
    ],
  },
  {
    id: 'lower',
    name: 'LOWER',
    label: 'Sexta',
    focus: 'Pernas + Metabólico 💥',
    cardioNote: '💥 CHAVE PRA BARRIGA — circuito metabólico integrado',
    exercises: [
      {
        id: 'lower1',
        name: 'Agachamento (Força)',
        sets: 3,
        reps: '8',
        rest: '120s',
        tip: 'Carga pesada, execução perfeita. Foco em força.',
        substitutes: ['Agachamento Smith', 'Leg Press 45°'],
        muscleGroup: 'Quadríceps',
      },
      {
        id: 'lower2',
        name: 'Stiff (Força)',
        sets: 3,
        reps: '10',
        rest: '90s',
        tip: 'Carga moderada-alta. Posterior e glúteos.',
        substitutes: ['Romeno com Halteres', 'Good Morning'],
        muscleGroup: 'Posterior',
      },
      {
        id: 'lower3',
        name: '🔥 Circuito: Kettlebell Swing',
        sets: 4,
        reps: '15',
        rest: '30-45s',
        tip: 'CIRCUITO: faça os 4 exercícios seguidos, descanse 30-45s e repita 3-4x. Explosão no quadril!',
        substitutes: ['Swing com Halter', 'Sumo Deadlift'],
        muscleGroup: 'Posterior + Core',
      },
      {
        id: 'lower4',
        name: '🔥 Circuito: Afundo',
        sets: 4,
        reps: '10 cada',
        rest: '0s (circuito)',
        tip: 'Sem descanso, vai direto pro próximo. Passo largo, joelho quase no chão.',
        substitutes: ['Búlgaro', 'Step Up'],
        muscleGroup: 'Quadríceps + Glúteo',
      },
      {
        id: 'lower5',
        name: '🔥 Circuito: Leg Press',
        sets: 4,
        reps: '15',
        rest: '0s (circuito)',
        tip: 'Carga leve-moderada. Velocidade controlada.',
        substitutes: ['Agachamento Goblet', 'Hack Squat'],
        muscleGroup: 'Quadríceps',
      },
      {
        id: 'lower6',
        name: '🔥 Circuito: Burpee',
        sets: 4,
        reps: '8',
        rest: '30-45s',
        tip: 'Full body, explosivo. Depois descanse 30-45s antes de repetir o circuito.',
        substitutes: ['Mountain Climber 20x', 'Jump Squat 12x'],
        muscleGroup: 'Full Body',
      },
    ],
  },
];

export const cardioProtocol = {
  title: 'Protocolo de Cardio Estratégico',
  description: 'Cardio estratégico: LISS pós-treino queima gordura, HIIT acelera metabolismo, metabólico na sexta seca barriga.',
  sessions: [
    {
      day: 'Segunda (Pós-PUSH)',
      type: 'LISS',
      duration: '20 min',
      intensity: 'FC 120-135 bpm',
      activity: 'Caminhada inclinada (10-12%)',
      tip: 'Velocidade 5.5-6.5 km/h. Não segure nos apoios.',
    },
    {
      day: 'Terça (Pós-PULL)',
      type: 'HIIT',
      duration: '15 min',
      intensity: 'Máx / Recuperação',
      activity: '30s sprint + 1min leve',
      tip: '10 rounds. Se não aguentar, reduza pra 20s sprint.',
    },
    {
      day: 'Quarta (Pós-LEGS)',
      type: 'LISS',
      duration: '15-20 min',
      intensity: 'FC 120-135 bpm',
      activity: 'Elíptico ou Caminhada',
      tip: 'Dia de perna: prefira elíptico (menos impacto nos joelhos).',
    },
    {
      day: 'Quinta (Pós-UPPER)',
      type: 'HIIT',
      duration: '15 min',
      intensity: 'Máx / Recuperação',
      activity: '30s sprint + 1min leve',
      tip: '10 rounds na bike ou esteira.',
    },
    {
      day: 'Sexta (LOWER)',
      type: 'METABÓLICO',
      duration: 'Integrado',
      intensity: 'Circuito',
      activity: 'Circuito metabólico (parte 2 do treino)',
      tip: '💥 O circuito da sexta É o cardio. Esse dia mais seca barriga!',
    },
    {
      day: 'Sábado (Opcional)',
      type: 'LISS',
      duration: '30-40 min',
      intensity: 'FC 110-125 bpm',
      activity: 'Caminhada ao ar livre',
      tip: 'Recuperação ativa. Bom pra mente e corpo.',
    },
  ],
  rules: [
    'Cardio SEMPRE depois da musculação, nunca antes',
    'Em jejum NÃO — com seu metabolismo basal, seria catabolismo',
    'Se estiver muito cansado do treino, faça LISS no lugar de HIIT',
    'Meta semanal: mínimo 100 min de cardio total',
    'Sábado: caminhada ao ar livre 30-40 min (opcional mas recomendado)',
    'Domingo: DESCANSO total',
  ],
};

export const progressionTips = {
  title: '🧠 Diferencial do Seu Treino',
  items: [
    {
      icon: '🔥',
      title: 'Progressão Inteligente',
      description: 'Aumente carga semanalmente OU repita com melhor execução. Anote tudo!',
    },
    {
      icon: '🔥',
      title: 'Cardio Estratégico',
      description: 'Pós-treino leve (queima gordura) + HIIT (acelera metabolismo) = combo matador.',
    },
    {
      icon: '🔥',
      title: 'Treino Metabólico (Sexta)',
      description: '👉 ISSO é ouro pra gordura visceral. O circuito da sexta é o dia que mais seca barriga!',
    },
  ],
};

export const antiFailProtocol = {
  title: '🔒 PROTOCOLO ANTI-FALHA',
  subtitle: 'Sistema para nunca sair dos trilhos',
  rules: [
    {
      icon: '🎯',
      title: 'Regra dos 2 Dias',
      description: 'NUNCA falhe 2 dias seguidos. Faltou segunda? Terça é OBRIGATÓRIA.',
    },
    {
      icon: '🍫',
      title: 'Regra do Doce',
      description: 'Vontade de doce? 1 quadrado de chocolate 70%+ é permitido. Gelatina zero açúcar é livre.',
    },
    {
      icon: '📱',
      title: 'Alarme das 20:00',
      description: 'Coloque um alarme diário às 20:00 — é o gatilho pra ir pra academia.',
    },
    {
      icon: '🏋️',
      title: 'Treino Mínimo Viável',
      description: 'Dia ruim? Faça pelo menos 3 exercícios compostos. Melhor que nada.',
    },
    {
      icon: '🍽️',
      title: 'Fim de Semana',
      description: 'Sábado: 1 refeição livre (não o dia inteiro). Domingo: volta ao plano.',
    },
    {
      icon: '💊',
      title: 'Escitalopram + Treino',
      description: 'Tome o remédio no mesmo horário. O treino potencializa o efeito. Não pule nenhum.',
    },
    {
      icon: '😴',
      title: 'Sono é Anabólico',
      description: 'Meta: dormir até 00:00. Cada hora antes da meia-noite vale dobro pra recuperação.',
    },
    {
      icon: '📊',
      title: 'Pesagem Semanal',
      description: 'Pese SEMPRE segunda de manhã, em jejum, após ir ao banheiro. Mesmo horário.',
    },
  ],
};

export const defaultDietPlan = {
  title: 'Plano Alimentar',
  targetCalories: 1800,
  macros: {
    protein: { grams: 187, pct: 42 },
    carbs: { grams: 150, pct: 33 },
    fat: { grams: 50, pct: 25 },
  },
  meals: [
    {
      id: 'm1',
      time: '08:30',
      name: 'Café da Manhã',
      items: ['3 ovos mexidos', '1 fatia de pão integral', '1 fatia de queijo branco', 'Café sem açúcar'],
      calories: 380,
    },
    {
      id: 'm2',
      time: '11:30',
      name: 'Lanche da Manhã',
      items: ['1 scoop whey + água', '1 banana'],
      calories: 250,
    },
    {
      id: 'm3',
      time: '13:30',
      name: 'Almoço',
      items: ['200g frango grelhado', '100g arroz integral', 'Salada verde à vontade', '1 col. sopa azeite'],
      calories: 480,
    },
    {
      id: 'm4',
      time: '16:30',
      name: 'Lanche da Tarde',
      items: ['200g iogurte grego natural', '30g granola', '5 castanhas'],
      calories: 250,
    },
    {
      id: 'm5',
      time: '20:00',
      name: 'Pré-Treino',
      items: ['1 banana', '1 col. sopa pasta de amendoim'],
      calories: 200,
    },
    {
      id: 'm6',
      time: '23:00',
      name: 'Pós-Treino / Jantar',
      items: ['200g carne magra ou peixe', 'Legumes refogados', '1 batata doce média'],
      calories: 440,
    },
  ],
  tips: [
    'Beba no mínimo 3L de água por dia',
    'Doce: troque por gelatina zero ou chocolate 70%',
    'Final de semana: 1 refeição livre no sábado. Domingo normal.',
    'Se sentir fome: pepino, cenoura crua ou gelatina zero',
    'Não pule refeições — distribua proteína ao longo do dia',
  ],
};
