export interface Exercise {
  id: string;
  name: string;
  sets: number;
  reps: string;
  rest: string;
  tip: string;
  substitutes: string[];
  muscleGroup: string;
}

export interface TrainingDay {
  id: string;
  name: string;
  label: string;
  focus: string;
  exercises: Exercise[];
}

export const trainingPlan: TrainingDay[] = [
  {
    id: 'a',
    name: 'Treino A',
    label: 'Segunda',
    focus: 'Peito + Tríceps',
    exercises: [
      {
        id: 'a1',
        name: 'Supino Reto com Barra',
        sets: 4,
        reps: '8-12',
        rest: '90s',
        tip: 'Desça a barra até o peito, cotovelos a 45°. Controle a descida (2s).',
        substitutes: ['Supino com Halteres', 'Supino Máquina'],
        muscleGroup: 'Peitoral',
      },
      {
        id: 'a2',
        name: 'Supino Inclinado Halteres',
        sets: 4,
        reps: '10-12',
        rest: '75s',
        tip: 'Banco a 30-45°. Abra bem na descida, junte no topo.',
        substitutes: ['Supino Inclinado Barra', 'Crossover de Baixo p/ Cima'],
        muscleGroup: 'Peitoral Superior',
      },
      {
        id: 'a3',
        name: 'Crossover',
        sets: 3,
        reps: '12-15',
        rest: '60s',
        tip: 'Mantenha cotovelos levemente flexionados. Sinta o squeeze no centro.',
        substitutes: ['Peck Deck', 'Crucifixo Halteres'],
        muscleGroup: 'Peitoral',
      },
      {
        id: 'a4',
        name: 'Tríceps Corda',
        sets: 4,
        reps: '10-12',
        rest: '60s',
        tip: 'Abra a corda nas pontas. Cotovelos fixos ao corpo.',
        substitutes: ['Tríceps Barra Reta', 'Tríceps Francês'],
        muscleGroup: 'Tríceps',
      },
      {
        id: 'a5',
        name: 'Tríceps Testa',
        sets: 3,
        reps: '10-12',
        rest: '60s',
        tip: 'Desça a barra até a testa. Cotovelos apontando pro teto.',
        substitutes: ['Tríceps Mergulho', 'Tríceps Kickback'],
        muscleGroup: 'Tríceps',
      },
    ],
  },
  {
    id: 'b',
    name: 'Treino B',
    label: 'Terça',
    focus: 'Costas + Bíceps',
    exercises: [
      {
        id: 'b1',
        name: 'Puxada Frontal',
        sets: 4,
        reps: '8-12',
        rest: '90s',
        tip: 'Puxe até o peito, escápulas retraídas. Segure 1s embaixo.',
        substitutes: ['Barra Fixa', 'Puxada Triângulo'],
        muscleGroup: 'Dorsal',
      },
      {
        id: 'b2',
        name: 'Remada Curvada',
        sets: 4,
        reps: '8-12',
        rest: '90s',
        tip: 'Tronco a 45°. Puxe a barra para o abdômen. Sem impulso.',
        substitutes: ['Remada Cavalinho', 'Remada Unilateral'],
        muscleGroup: 'Dorsal',
      },
      {
        id: 'b3',
        name: 'Remada Baixa (Triângulo)',
        sets: 3,
        reps: '10-12',
        rest: '75s',
        tip: 'Peito pra frente. Puxe até o abdômen, squeeze nas costas.',
        substitutes: ['Remada Sentada Aberta', 'Pullover Máquina'],
        muscleGroup: 'Dorsal',
      },
      {
        id: 'b4',
        name: 'Rosca Direta Barra',
        sets: 4,
        reps: '10-12',
        rest: '60s',
        tip: 'Cotovelos fixos. Suba com controle, desça em 2s.',
        substitutes: ['Rosca Halteres Alternada', 'Rosca Scott'],
        muscleGroup: 'Bíceps',
      },
      {
        id: 'b5',
        name: 'Rosca Martelo',
        sets: 3,
        reps: '10-12',
        rest: '60s',
        tip: 'Pegada neutra. Mantenha cotovelos grudados no corpo.',
        substitutes: ['Rosca Inversa', 'Rosca Concentrada'],
        muscleGroup: 'Bíceps',
      },
    ],
  },
  {
    id: 'c',
    name: 'Treino C',
    label: 'Quarta',
    focus: 'Pernas (Quadríceps + Posterior)',
    exercises: [
      {
        id: 'c1',
        name: 'Agachamento Livre',
        sets: 4,
        reps: '8-10',
        rest: '120s',
        tip: 'Pés na largura dos ombros. Desça até 90°. Core contraído.',
        substitutes: ['Leg Press 45°', 'Agachamento Smith'],
        muscleGroup: 'Quadríceps',
      },
      {
        id: 'c2',
        name: 'Leg Press 45°',
        sets: 4,
        reps: '10-12',
        rest: '90s',
        tip: 'Pés no meio da plataforma. Não trave os joelhos no topo.',
        substitutes: ['Hack Squat', 'Agachamento Búlgaro'],
        muscleGroup: 'Quadríceps',
      },
      {
        id: 'c3',
        name: 'Cadeira Extensora',
        sets: 3,
        reps: '12-15',
        rest: '60s',
        tip: 'Suba totalmente e segure 1s no topo. Desça controlado.',
        substitutes: ['Extensão Unilateral', 'Sissy Squat'],
        muscleGroup: 'Quadríceps',
      },
      {
        id: 'c4',
        name: 'Mesa Flexora',
        sets: 4,
        reps: '10-12',
        rest: '75s',
        tip: 'Quadril colado no banco. Contraia glúteos e posteriores.',
        substitutes: ['Stiff', 'Flexora em Pé'],
        muscleGroup: 'Posterior',
      },
      {
        id: 'c5',
        name: 'Panturrilha em Pé',
        sets: 4,
        reps: '15-20',
        rest: '45s',
        tip: 'Amplitude máxima. Segure 2s no topo, desça esticando.',
        substitutes: ['Panturrilha Sentado', 'Panturrilha no Leg'],
        muscleGroup: 'Panturrilha',
      },
    ],
  },
  {
    id: 'd',
    name: 'Treino D',
    label: 'Quinta',
    focus: 'Ombros + Abdômen',
    exercises: [
      {
        id: 'd1',
        name: 'Desenvolvimento Halteres',
        sets: 4,
        reps: '8-12',
        rest: '90s',
        tip: 'Sentado, costas apoiadas. Suba até quase travar os cotovelos.',
        substitutes: ['Desenvolvimento Barra', 'Desenvolvimento Arnold'],
        muscleGroup: 'Deltóide',
      },
      {
        id: 'd2',
        name: 'Elevação Lateral',
        sets: 4,
        reps: '12-15',
        rest: '60s',
        tip: 'Cotovelos levemente flexionados. Suba até a altura dos ombros.',
        substitutes: ['Elevação Lateral Cabo', 'Elevação Lateral Máquina'],
        muscleGroup: 'Deltóide Lateral',
      },
      {
        id: 'd3',
        name: 'Elevação Frontal',
        sets: 3,
        reps: '12-15',
        rest: '60s',
        tip: 'Alternada ou simultânea. Não balance o tronco.',
        substitutes: ['Elevação Frontal Barra', 'Elevação Frontal Cabo'],
        muscleGroup: 'Deltóide Anterior',
      },
      {
        id: 'd4',
        name: 'Face Pull',
        sets: 3,
        reps: '15-20',
        rest: '60s',
        tip: 'Puxe para o rosto, rotação externa. Essencial pra postura!',
        substitutes: ['Crucifixo Inverso', 'Band Pull Apart'],
        muscleGroup: 'Deltóide Posterior',
      },
      {
        id: 'd5',
        name: 'Abdominal Infra (Elevação de Pernas)',
        sets: 4,
        reps: '15-20',
        rest: '45s',
        tip: 'Pernas retas, suba até 90°. Controle a descida.',
        substitutes: ['Abdominal Máquina', 'Prancha'],
        muscleGroup: 'Abdômen',
      },
      {
        id: 'd6',
        name: 'Prancha',
        sets: 3,
        reps: '45-60s',
        rest: '30s',
        tip: 'Corpo reto da cabeça aos pés. Core 100% contraído.',
        substitutes: ['Prancha Lateral', 'Abdominal Bicicleta'],
        muscleGroup: 'Core',
      },
    ],
  },
  {
    id: 'e',
    name: 'Treino E',
    label: 'Sexta',
    focus: 'Full Body + Pontos Fracos',
    exercises: [
      {
        id: 'e1',
        name: 'Supino Reto (Leve)',
        sets: 3,
        reps: '12-15',
        rest: '60s',
        tip: 'Foco em conexão mente-músculo. Carga moderada.',
        substitutes: ['Flexão', 'Crossover'],
        muscleGroup: 'Peitoral',
      },
      {
        id: 'e2',
        name: 'Puxada Supinada',
        sets: 3,
        reps: '10-12',
        rest: '75s',
        tip: 'Pegada supinada. Foco em dorsais e bíceps.',
        substitutes: ['Barra Fixa Supinada', 'Remada Baixa Supinada'],
        muscleGroup: 'Dorsal + Bíceps',
      },
      {
        id: 'e3',
        name: 'Agachamento Búlgaro',
        sets: 3,
        reps: '10-12 (cada)',
        rest: '75s',
        tip: 'Pé de trás no banco. Desça até o joelho quase tocar o chão.',
        substitutes: ['Afundo', 'Leg Press Unilateral'],
        muscleGroup: 'Quadríceps + Glúteo',
      },
      {
        id: 'e4',
        name: 'Desenvolvimento Arnold',
        sets: 3,
        reps: '10-12',
        rest: '60s',
        tip: 'Comece com palmas voltadas pra você, gire durante a subida.',
        substitutes: ['Desenvolvimento Halteres', 'Elevação Lateral'],
        muscleGroup: 'Deltóide',
      },
      {
        id: 'e5',
        name: 'Abdominal Oblíquo',
        sets: 3,
        reps: '15 (cada lado)',
        rest: '45s',
        tip: 'Rotação controlada. Sinta o oblíquo contrair.',
        substitutes: ['Prancha Lateral', 'Wood Chop Cabo'],
        muscleGroup: 'Oblíquos',
      },
    ],
  },
];

export const cardioProtocol = {
  title: 'Protocolo de Cardio — Queima de Gordura',
  description: 'Cardio pós-treino para maximizar a queima de gordura sem comprometer a massa muscular.',
  sessions: [
    {
      day: 'Segunda (Pós-Treino A)',
      type: 'LISS',
      duration: '25 min',
      intensity: 'FC 120-135 bpm',
      activity: 'Esteira (caminhada inclinada 10-12%)',
      tip: 'Velocidade 5.5-6.5 km/h. Não segure nos apoios.',
    },
    {
      day: 'Terça (Pós-Treino B)',
      type: 'HIIT',
      duration: '15 min',
      intensity: 'Máx / Recuperação',
      activity: 'Bike: 30s sprint + 60s leve',
      tip: '10 rounds. Se não aguentar, reduza pra 20s sprint.',
    },
    {
      day: 'Quarta (Pós-Treino C)',
      type: 'LISS',
      duration: '30 min',
      intensity: 'FC 120-135 bpm',
      activity: 'Elíptico ou Caminhada',
      tip: 'Dia de perna: prefira elíptico (menos impacto nos joelhos).',
    },
    {
      day: 'Quinta (Pós-Treino D)',
      type: 'MISS',
      duration: '20 min',
      intensity: 'FC 135-150 bpm',
      activity: 'Esteira (trote leve)',
      tip: 'Moderado. Velocidade 7-8 km/h.',
    },
    {
      day: 'Sexta (Pós-Treino E)',
      type: 'HIIT',
      duration: '12 min',
      intensity: 'Tabata Style',
      activity: 'Bike: 20s all-out + 10s rest',
      tip: '8 rounds (4 min) x3 blocos com 1min descanso entre.',
    },
  ],
  rules: [
    'Cardio SEMPRE depois da musculação, nunca antes',
    'Em jejum NÃO — com seu metabolismo basal, seria catabolismo',
    'Se estiver muito cansado do treino, faça LISS no lugar de HIIT',
    'Meta semanal: mínimo 100 min de cardio total',
    'Sábado/Domingo: caminhada ao ar livre 30-40 min (opcional mas recomendado)',
  ],
};

export const antiFailProtocol = {
  title: '🔒 PROTOCOLO ANTI-FALHA',
  subtitle: 'Sistema para nunca sair dos trilhos',
  rules: [
    {
      icon: '🎯',
      title: 'Regra dos 2 Dias',
      description: 'NUNCA falhe 2 dias seguidos. Faltou segunda? Terça é OBRIGATÓRIA.',
    },
    {
      icon: '🍫',
      title: 'Regra do Doce',
      description: 'Vontade de doce? 1 quadrado de chocolate 70%+ é permitido. Gelatina zero açúcar é livre.',
    },
    {
      icon: '📱',
      title: 'Alarme das 20:00',
      description: 'Coloque um alarme diário às 20:00 — é o gatilho pra ir pra academia.',
    },
    {
      icon: '🏋️',
      title: 'Treino Mínimo Viável',
      description: 'Dia ruim? Faça pelo menos 3 exercícios compostos. Melhor que nada.',
    },
    {
      icon: '🍽️',
      title: 'Fim de Semana',
      description: 'Sábado: 1 refeição livre (não o dia inteiro). Domingo: volta ao plano.',
    },
    {
      icon: '💊',
      title: 'Escitalopram + Treino',
      description: 'Tome o remédio no mesmo horário. O treino potencializa o efeito. Não pule nenhum.',
    },
    {
      icon: '😴',
      title: 'Sono é Anabólico',
      description: 'Meta: dormir até 00:00. Cada hora antes da meia-noite vale dobro pra recuperação.',
    },
    {
      icon: '📊',
      title: 'Pesagem Semanal',
      description: 'Pese SEMPRE segunda de manhã, em jejum, após ir ao banheiro. Mesmo horário.',
    },
  ],
};

export const dietPlan = {
  title: 'Plano Alimentar',
  targetCalories: 1800,
  macros: {
    protein: { grams: 187, pct: 42 },
    carbs: { grams: 150, pct: 33 },
    fat: { grams: 50, pct: 25 },
  },
  meals: [
    {
      time: '08:30',
      name: 'Café da Manhã',
      items: ['3 ovos mexidos', '1 fatia de pão integral', '1 fatia de queijo branco', 'Café sem açúcar'],
      calories: 380,
    },
    {
      time: '11:30',
      name: 'Lanche da Manhã',
      items: ['1 scoop whey + água', '1 banana'],
      calories: 250,
    },
    {
      time: '13:30',
      name: 'Almoço',
      items: ['200g frango grelhado', '100g arroz integral', 'Salada verde à vontade', '1 col. sopa azeite'],
      calories: 480,
    },
    {
      time: '16:30',
      name: 'Lanche da Tarde',
      items: ['200g iogurte grego natural', '30g granola', '5 castanhas'],
      calories: 250,
    },
    {
      time: '20:00',
      name: 'Pré-Treino',
      items: ['1 banana', '1 col. sopa pasta de amendoim'],
      calories: 200,
    },
    {
      time: '23:00',
      name: 'Pós-Treino / Jantar',
      items: ['200g carne magra ou peixe', 'Legumes refogados', '1 batata doce média'],
      calories: 440,
    },
  ],
  tips: [
    'Beba no mínimo 3L de água por dia',
    'Doce: troque por gelatina zero ou chocolate 70%',
    'Final de semana: 1 refeição livre no sábado. Domingo normal.',
    'Se sentir fome: pepino, cenoura crua ou gelatina zero',
    'Não pule refeições — distribua proteína ao longo do dia',
  ],
};
