/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreinoRouteImport } from './routes/treino'
import { Route as FerramentasRouteImport } from './routes/ferramentas'
import { Route as DietaRouteImport } from './routes/dieta'
import { Route as CorpoRouteImport } from './routes/corpo'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as CardioRouteImport } from './routes/cardio'
import { Route as IndexRouteImport } from './routes/index'

const TreinoRoute = TreinoRouteImport.update({
  id: '/treino',
  path: '/treino',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasRoute = FerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)
const DietaRoute = DietaRouteImport.update({
  id: '/dieta',
  path: '/dieta',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpoRoute = CorpoRouteImport.update({
  id: '/corpo',
  path: '/corpo',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const CardioRoute = CardioRouteImport.update({
  id: '/cardio',
  path: '/cardio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cardio': typeof CardioRoute
  '/checklist': typeof ChecklistRoute
  '/corpo': typeof CorpoRoute
  '/dieta': typeof DietaRoute
  '/ferramentas': typeof FerramentasRoute
  '/treino': typeof TreinoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cardio': typeof CardioRoute
  '/checklist': typeof ChecklistRoute
  '/corpo': typeof CorpoRoute
  '/dieta': typeof DietaRoute
  '/ferramentas': typeof FerramentasRoute
  '/treino': typeof TreinoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cardio': typeof CardioRoute
  '/checklist': typeof ChecklistRoute
  '/corpo': typeof CorpoRoute
  '/dieta': typeof DietaRoute
  '/ferramentas': typeof FerramentasRoute
  '/treino': typeof TreinoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cardio'
    | '/checklist'
    | '/corpo'
    | '/dieta'
    | '/ferramentas'
    | '/treino'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cardio'
    | '/checklist'
    | '/corpo'
    | '/dieta'
    | '/ferramentas'
    | '/treino'
  id:
    | '__root__'
    | '/'
    | '/cardio'
    | '/checklist'
    | '/corpo'
    | '/dieta'
    | '/ferramentas'
    | '/treino'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardioRoute: typeof CardioRoute
  ChecklistRoute: typeof ChecklistRoute
  CorpoRoute: typeof CorpoRoute
  DietaRoute: typeof DietaRoute
  FerramentasRoute: typeof FerramentasRoute
  TreinoRoute: typeof TreinoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treino': {
      id: '/treino'
      path: '/treino'
      fullPath: '/treino'
      preLoaderRoute: typeof TreinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas': {
      id: '/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof FerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dieta': {
      id: '/dieta'
      path: '/dieta'
      fullPath: '/dieta'
      preLoaderRoute: typeof DietaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corpo': {
      id: '/corpo'
      path: '/corpo'
      fullPath: '/corpo'
      preLoaderRoute: typeof CorpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardio': {
      id: '/cardio'
      path: '/cardio'
      fullPath: '/cardio'
      preLoaderRoute: typeof CardioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardioRoute: CardioRoute,
  ChecklistRoute: ChecklistRoute,
  CorpoRoute: CorpoRoute,
  DietaRoute: DietaRoute,
  FerramentasRoute: FerramentasRoute,
  TreinoRoute: TreinoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
